---
name: Molecule
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '30 1 * * 3'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Pull Lint image
        run: docker pull -q schmitzis/molecule:lint

      - name: Ansible Linting
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/git -w /git schmitzis/molecule:lint ansible-lint -p --offline /git

      - name: Yaml Linting
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/git -w /git schmitzis/molecule:lint yamllint -f parsable /git

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: ubuntu-20.04
            test_type: unit
          - distro: ubuntu-22.04
            test_type: unit
    steps:
      - uses: Rheinwerk/molecule@v1
        with:
          distro: ${{ matrix.distro }}
          test_type: ${{ matrix.test_type }}
